name: "Ruby CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
defaults:
  run:
    working-directory: ./backend
env:
  PROJECT_DIR: ./backend
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: medical-exams
        ports:
          - "5432:5432"
      redis:
        image: redis
        ports:
          - "6379:6379"
    env:
      DATABASE_URL: localhost
      RACK_ENV: test
      REDIS_URL: redis://redis:6379/0
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        working-directory: ${{env.PROJECT_DIR}}
    - name: Set up Ruby and Gems
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.4
        bundler-cache: true
        working-directory: ${{env.PROJECT_DIR}}
    - name: Run tests
      run: bundle exec rspec

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          working-directory: ${{env.PROJECT_DIR}}
      - name: Set up Ruby and Gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4
          bundler-cache: true
          working-directory: ${{env.PROJECT_DIR}}
      - name: Install Bundler Audit
        run: gem install bundler-audit
      - name: Security audit dependencies
        run: bundle-audit check --update
      - name: Lint Ruby files
        run: bundle exec rubocop